### ISSUE TITLE
使用python3.4安装everytools-0.0.1.2.tar.gz源码包报错

### ISSUE THREAD

**Issue by KuYouRan** [yangjiada/everytools#2]
报错内容,如果想看有颜色区分的报错,可以查看图片:
![Snipaste_2024-11-14_18-01-37](https://github.com/user-attachments/assets/977c890e-6a62-43a4-a846-19a6baf68e28)

C:\Users\rkey\Desktop\测试\添加视频路径>pip3.4 install C:\Users\rkey\Downloads\everytools-0.0.1.2.tar.gz
Unpacking c:\users\rkey\downloads\everytools-0.0.1.2.tar.gz
  Running setup.py (path:C:\Users\rkey\AppData\Local\Temp\pip-9bcw975h-build\setup.py) egg_info for package from file:///C:/Users/rkey/Downloads/everytools-0.0.1.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\rkey\AppData\Local\Temp\pip-9bcw975h-build\setup.py", line 8, in <module>
        INSTALL_PACKAGES = open(path.join(DIR, 'requirements.txt')).read().splitlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rkey\\AppData\\Local\\Temp\\pip-9bcw975h-build\\requirements.txt'    
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\rkey\AppData\Local\Temp\pip-9bcw975h-build\setup.py", line 8, in <module>

    INSTALL_PACKAGES = open(path.join(DIR, 'requirements.txt')).read().splitlines()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rkey\\AppData\\Local\\Temp\\pip-9bcw975h-build\\requirements.txt'        

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\rkey\AppData\Local\Temp\pip-9bcw975h-build
Storing debug log for failure in C:\Users\rkey\pip\pip.log

**Comment by yangjiada** [comment]
请使用英文路径，另外建议在python3.8或以上版本上安装，3.4太旧了。
